config/routes.rb
Rails.application.routes.draw do
  root to: "game_rooms#index"
  # devise_scope :user do
  #   root "users/sessions#new"
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  resources :users, only: %i!show!
  resources :game_rooms, only: %i!index new create edit update show destroy!
  resources :participants, only: %i! create update destroy!
  resources :game_room_messages, only: %i! create destroy!

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/game_room_message.rb
class GameRoomMessage < ApplicationRecord
  belongs_to :game_room
  belongs_to :write_user, class_name: 'User'
end

app/controllers/game_room_messages_controller.rb
class GameRoomMessagesController < ApplicationController

  def create
    @message = GameRoomMessage.new(game_room_id: params[:game_room_message][:room_id], write_user_id: current_user.id, body: params[:game_room_message][:body])
    @game_room = GameRoom.find(params[:game_room_message][:room_id])
    @participants = @game_room.participants
    @room_message = @game_room.game_room_messages

    respond_to do |format|
      if @message.save
        format.html { redirect_to game_room_path(params[:game_room_message][:room_id])}
        format.js { render :index }
      else
        format.html { redirect_to game_room_path(params[:game_room_message][:room_id]), notice: 'コメントに失敗しました'}
      end
    end

  end

  def destroy
    respond_to do |format|
      if GameRoomMessage.find(params[:id]).destroy
        format.html { redirect_to game_room_path(params[:room_id])}
        format.js { render :index }
      else
        format.html { redirect_to game_room_path(params[:game_room_message][:room_id])}
      end
    end
  end

end

app/views/game_room_messages/_form.slim
  = form_with(model: GameRoomMessage.new, url: game_room_messages_path) do |f|
    .field.mt20
      = f.text_area :body, class: "form-control"
      = f.text_field :user_id, value: current_user.id, type: "hidden"

      = f.hidden_field :room_id, value: room_id
      = f.submit "メッセージを送る", class:"mt10"

app/views/game_room_messages/_game_room_message.slim
.message
  = game_room_message.body
  / = @messages.each do |message|
  /   p = message.body

app/views/game_room_messages/_index.slim
.message
  - if @participants.find_by(user_id: current_user.id)
    h3.mb20 メッセージ一覧
    - @room_message.each do |m|
      .room_message.mt20
        p = m.write_user.name
        p.mt4 = m.body
        p.mt4 = m.created_at.strftime("%m月%d日 %H:%M:%S")
        p = link_to t('game_rooms.show.delete_message'), game_room_message_path(id: m.id, room_id: @game_room.id), method: :DELETE

app/views/game_room_messages/index.js.erb
$("#comments_area").html("<%= j(render 'game_room_messages/index') %>");

$("#game_room_message_body").val("");