config/routes.rb
Rails.application.routes.draw do
  root to: "game_rooms#index"
  # devise_scope :user do
  #   root "users/sessions#new"
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  resources :users, only: %i!show!
  resources :game_rooms, only: %i!index new create edit update show destroy!
  resources :participants, only: %i! create update destroy!
  resources :game_room_messages, only: %i! create destroy!

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/game_room.rb
class GameRoom < ApplicationRecord

  require "date"

  has_many :participants, dependent: :destroy
  has_many :game_room_messages, dependent: :destroy
  has_many :users, through: :participants

  validates :game_title, presence: true
  validates :start_time, presence: true
  validates :play_time, presence: true
  validates :play_device, presence: true
  validates :room_name, presence: true
  validate :date_not_before_today
  validate :date_not_after_one_year_later

  scope :valid_time_room, -> {where('start_time >= ?', Date.today)}

  enum play_device:{
    PlayStation: 0,
    Nintendo: 1,
    Steam: 2,
  }

  def self.search_owner_info(game_room_id)
    self.find(game_room_id).participants.owner
  end

  def user_exists?(current_user_id)
    self.participants.find_by(user_id: current_user_id).present?
  end

  def user_not_owner?(user)
    self.participants.owner.user_id != user.id
  end

  def date_not_before_today
    errors.add(:start_time, "は今日以降のものを選択してください") if start_time.nil? || start_time < Date.today
  end

  def date_not_after_one_year_later
    day = Date.today
    one_year_later = day.next_year(1)
    errors.add(:start_time, "は一年以内を選択してください") if start_time.nil? || start_time > one_year_later
  end

end

app/controllers/game_rooms_controller.rb
class GameRoomsController < ApplicationController
  before_action :authenticate_user!

  require 'date'

  before_action :set_game_title

  helper_method :condition_fullfill, :need_conditions, :can_make_request, :find_owner_info

  PER = 12

  def index
    @q = GameRoom.all.includes([:participants, :users]).ransack(params[:q])
    @game_rooms = @q.result(distinct: true).valid_time_room.page(params[:page]).per(PER)
    if params[:keyword]
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword],tag_ids: 1005402)
    end
  end

  def new
    @game_room = GameRoom.new
  end

  def create
    @game_room = GameRoom.new(game_room_params)
    @game_room.participants.build(user_id: current_user.id, state: 0)

    if @game_room.save
      redirect_to game_rooms_path
      flash[:notice] = t('game_rooms.index.create_room')
    else
      render "new"
    end
  end

  def show
    @game_room = GameRoom.find(params[:id])
    if @game_room.participants.search_current_user(current_user.id).blank?
      redirect_to game_rooms_path
    end
    @participants = @game_room.participants
    @owner = @participants.owner
    @room_message = @game_room.game_room_messages
    @messages = @game_room.game_room_messages
  end

  def edit
    @game_room = GameRoom.find(params[:id])
  end

  def update
    @game_room = GameRoom.find(params[:id])
    if @game_room.update(game_room_params)
      redirect_to @game_room
    else
      render :edit
    end
  end

  def find_owner_info(gr)
    @owner = gr.participants.owner.user
  end
  # ownerではなく、ゲームルームに参加中でもなく参加希望も出していな状態かどうかチェックしている
  def can_make_request(gr)
    gr.user_not_owner?(current_user) && gr.user_exists?(current_user.id) == false ? true : false
  end

  # 一つでも[true,false]の組み合わせがあったらfalseになるメソッド(true,falseの組み合わせになったら、情報が足りていないということ),不足しているものがあるかどうかチェックするメソッド
  def condition_fullfill(user, gr)
    [
      [gr.available_twitter?, user.twitter_address.present?],
      [gr.available_skype?, user.skype_id.present?],
      [gr.available_discord?, user.discord_id.present?],
      [gr.play_device == "PlayStation", user.game_machines.check_playstation_id_present],
      [gr.play_device == "Nintendo", user.game_machines.check_steam_id_present],
      [gr.play_device == "Steam", user.game_machines.check_nintendo_id_present],
    ].all? do |pair|
      pair != [true,false]
    end
  end
 # 足りていない情報を出力するメソッド
  def need_conditions(user, gr)
    result = {}
    result.merge!(skype: user.skype_id.blank?) if gr.available_skype?
    result.merge!(discord: user.discord_id.blank?) if gr.available_discord?
    result.merge!(twitter: user.twitter_address.blank?) if gr.available_twitter?
    result.merge!(PlayStation: user.game_machines.find_by(game_device: "PlayStation").device_id.blank?) if gr.play_device == "PlayStation"
    result.merge!(Nintendo: user.game_machines.find_by(game_device: "Nintendo").device_id.blank?) if gr.play_device == "Nintendo"
    result.merge!(Steam: user.game_machines.find_by(game_device: "Steam").device_id.blank?) if gr.play_device == "Steam"
    result.select{|_, v| v == true}.keys
  end


  private
  def set_game_title
    @game_titles = [
      t('game_rooms.index.title1'),
      t('game_rooms.index.title2'),
      t('game_rooms.index.title3'),
      t('game_rooms.index.title4'),
      t('game_rooms.index.title5'),
      t('game_rooms.index.title6'),
      t('game_rooms.index.title7'),
      t('game_rooms.index.title8'),
    ]
  end

  def game_room_params
    params.require(:game_room).permit(:game_title, :comment, :vc_possible, :available_skype, :available_discord, :available_twitter, :available_ingame_vc, :start_time, :play_time, :play_device, :open_twitter, :close_info, :close_message, :room_name)
  end

  def sign_in?
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/helpers/game_rooms_helper.rb
module GameRoomsHelper
  def new_or_edit
    unless @game_room.id?
      game_rooms_path
    else
      game_room_path
    end
  end

end

app/views/game_rooms/_game_title_list.slim
table
  thead
    tr
      th 商品名
      th 価格
      th 画像
  tbody
    - if @items.present?
      - @items.each do |item|
        tr
          td= link_to item.name, "# item.url "
          td align="right"
            = number_with_delimiter(item.price)
            | 円
          td= image_tag item.medium_image_urls[0]

app/views/game_rooms/_index_input_form.slim
.container
    .row.mb-12
      .col-12
        button.btn.btn-primary.mb-12 data-target="#testModal#{gameroom.id}" data-toggle="modal" type="button" 参加条件を入力して参加
div id="testModal#{gameroom.id}" class="modal fade show" aria-hidden="true" aria-labelledby="basicModal" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        h4 class="modal-title" id="myModalLabel"&gt;必要な情報を登録してください
      .modal-body
        .test
          = form_for(current_user, url: user_registration_path, html: { method: :patch }) do |f|
            - need_conditions(current_user, gameroom).each do |info|
              - if info == :skype
                .group
                  = f.text_field :skype_id, required: true
                  span.highlight
                  span.bar
                  label = t('users.new.skype_id')
              - if info == :twitter
                .group
                  = f.text_field :twitter_address, required: true
                  span.highlight
                  span.bar
                  label = t('users.new.twitter_address')
              - if info == :discord
                .group
                  = f.text_field :discord_id, required: true
                  span.highlight
                  span.bar
                  label = t('users.new.discord_id')
              - if info == :PlayStation
                = f.fields_for :game_machines, current_user.game_machines.where(game_device: "PlayStation") do |gm|
                  .group
                    / = gm.text_field :game_device, disabled: :disabled, class: :device_field, required: true
                    span.highlight
                    span.bar
                    = gm.text_field :device_id, required: true
                    span.highlight
                    span.bar
                    label = t('users.new.device_account_need_playstation')
              - if info == :Steam
                = f.fields_for :game_machines, current_user.game_machines.where(user_id: current_user.id, game_device: "Steam") do |gm|
                  .group
                    / = gm.text_field :game_device, disabled: :disabled, class: :device_field, required: true
                    span.highlight
                    span.bar
                    = gm.text_field :device_id, required: true
                    span.highlight
                    span.bar
                    label = t('users.new.device_account_need_steam')
              - if info == :Nintendo
                = f.fields_for :game_machines, current_user.game_machines.where(user_id: current_user.id, game_device: "Nintendo") do |gm|
                  .group
                    / = gm.text_field :game_device, disabled: :disabled, class: :device_field, required: true
                    span.highlight
                    span.bar
                    = gm.text_field :device_id, required: true
                    span.highlight
                    span.bar
                    label = t('users.new.device_account_need_nintendo')


            input type="hidden" id="game_room_info" name="room_info" value="#{gameroom.id}"

            .action
            = f.submit t('users.edit.submit')

app/views/game_rooms/edit.slim
h1 = t('game_rooms.edit.title')
h3 = t('game_rooms.edit.notice')

- if @game_room.errors.any?
  #error_explanatsion
    ul
      - @game_room.errors.full_messages.each do |message|
        li = message


.game_room_edit
  = form_with(model: @game_room, url: new_or_edit, local: true) do |f|

    .form-group
      = f.label t('game_rooms.new.room_name'), class: "control-label"
      = f.text_field :room_name, class: "form-control"

    .form-group
      = f.label t('game_rooms.new.game_title', class: "control-label")
      = f.text_field :game_title, class: "form-control"

    .form-group
      = f.label t('game_rooms.new.comment', class: "control-label")
      = f.text_area :comment, class: "comment", placeholder: "募集の詳細。記入しておくことで他のユーザーが参加しやすくなるかもしれません。"

    .form-group
      = f.label t('game_rooms.new.vc', class: "control-label")
      .checkbox
        = f.check_box :vc_possible

    .form-group
      = f.label t('game_rooms.new.skype', class: "control-label")
      .checkbox
        = f.check_box :available_skype

    .form-group
      = f.label t('game_rooms.new.discord', class: "control-label")
      .checkbox
        = f.check_box :available_discord

    .form-group
      = f.label t('game_rooms.new.ingame', class: "control-label")
      .checkbox
        = f.check_box :available_ingame_vc

    .form-group
      = f.label t('game_rooms.new.twitter', class: "control-label")
      .checkbox
        = f.check_box :available_twitter

    .form-group
      = f.label t('game_rooms.new.start_time', class: "control-label")
      = f.datetime_field :start_time, min: Date.today

    .form-group
      = f.label t('game_rooms.new.play_time', class: "control-label")
      = f.select :play_time, [[t('game_rooms.new.1hour'), 1], [t('game_rooms.new.2hour'), 2], [t('game_rooms.new.3hour'), 3], [t('game_rooms.new.4hour'), 4], [t('game_rooms.new.5hour'), 5]], { selected: 1}, class: 'sample'

    .form-group
      = f.label t('game_rooms.new.play_device', class: "control-label")
      = f.select :play_device, GameRoom.play_devices.keys.to_a, {}

    .form-group
      = f.label t('game_rooms.new.open_twitter', class: "control-label")
      = f.check_box :open_twitter

    .form-group
      = f.label t('game_rooms.new.close_message', class: "control-label")
      = f.text_area :close_message, placeholder: "参加が確定した人に対してしてほしいこと、ゲームを始めるまでの簡単な流れを書いておくとスムーズにマッチングできるかもしれません。例）予定時間の前までにゲーム内でフレンド申請を送ってください", class: "close_message"

    .form-group
      = f.submit t('game_rooms.edit.submit')

app/views/game_rooms/index.slim
.index_field
  / .content
  /   #search-box
  /     = form_tag(game_rooms_path, method: :get) do
  /       = text_field_tag :good, "",  id: "good_search", name: "keyword", placeholder: "キーワードを打ち込んでください", style: "width: 200px;"
  /       button title="検索" type="submit"  検索
  /   h2 検索結果
  /   #good_list
  /     = render partial: 'game_title_list'

  = search_form_for @q do |f|
    = f.search_field :game_title_cont, class: "search_box", id: "game_title", placeholder: t('game_rooms.index.sarch_title')
    .game_tag.container.mt6
      h4.mb2.mt10 画像をクリックすると検索窓にタイトルが入ります
      ul.horizontal-list
        li.item
          button type="button" id="tag_1" class="image_btn"
            = image_tag 'https://media.contentapi.ea.com/content/dam/apex-legends/images/2019/01/apex-featured-image-16x9.jpg.adapt.crop191x100.1200w.jpg', size:'300x200'
          p.text-algin-center = link_to "引用元:Electronic Arts", "https://www.ea.com/"
        li.item
          button type="button" id="tag_2" class="image_btn"
            = image_tag 'https://pubg.dmm.com/images/official/base/pic_thumb_cover.jpg', size:'300x200'
          p.text-algin-center = link_to "引用元:PUBG DMM", "http://pubg.dmm.com/"
        li.item
          button type="button" id="tag_3" class="image_btn"
            = image_tag 'https://cdn2.unrealengine.com/Fortnite%2Fblog%2Fchapter-2-season-2-update%2F11BR_Evergreens_Blue_NewsHeader-1920x1080-77ade2f5f2bc0312b4978dcd7639adfe00211fe6.jpg', size:'300x200'
          p.text-algin-center = link_to "引用元:Epic Games", "https://www.epicgames.com/fortnite/ja/home"
        li.item
          button type="button" id="tag_4" class="image_btn"
            = image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR8RnfbyyTRZMFMOGhgDZabd6hhBVpPaBJu3KIfQtsnAa0rLj30', size:'300x200'
          p.text-algin-center = link_to "引用元:FF14公式", "https://jp.finalfantasyxiv.com/"

        li.item
          button type="button" id="tag_5" class="image_btn"
            = image_tag 'https://sce.scene7.com/is/image/playstation/pljm16320_640x360?$JAcat_BnrS$', size:'300x200'
          p.text-algin-center = link_to "引用元:DeadByDayLight"
        li.item
          button type="button" id="tag_6" class="image_btn"
            = image_tag 'https://www.pokemon.co.jp/ex/sword_shield/assets/lineup-package01.png', size:'300x200'
          p.text-algin-center = link_to "引用元:任天堂・クリーチャーズ・ゲームフリーク Arts", "https://www.pokemon.co.jp/"
        li.item
          button type="button" id="tag_7" class="image_btn"
            = image_tag 'https://sce.scene7.com/is/image/playstation/pljm16110_s21?$JAcat_CapL$', size:'300x200'
          p.text-algin-center = link_to "引用元: モンスターハンター World公式", "http://www.capcom.co.jp/monsterhunter/world/"
        li.item
          button type="button" id="tag_8" class="image_btn"
            = image_tag 'https://www.smashbros.com/assets_v2/img/top/hero05.jpg', size:'300x200'
          / p.text-algin-center 大乱闘スマッシュブラザーズ
          p.text-algin-center = link_to "引用元: 大乱闘スマッシュブラザーズ公式サイト", "https://www.smashbros.com/ja_JP/"

      / - @game_titles.each_with_index do |title, x, image_url, sorce|
      /   button type="button" class="btn btn-primary mr6 mb6" id="tag_#{x + 1}"
      /     = title


      .index_search_zone
        p = f.label t('game_rooms.index.sarch_vc_possible')
        / .custom-control.custom-radio
        /   input#defaultUnchecked.custom-control-input name="defaultExampleRadios" type="radio" /
        /   label.custom-control-label for="defaultUnchecked"  Default unchecked

        | #{f.radio_button :vc_possible_eq, '', id: "vc_possible_index_none", checked: true} #{t('game_rooms.index.no_select')}
        | #{f.radio_button :vc_possible_eq, true, id: "vc_possible_index"} #{t('game_rooms.index.sarch_vc_true')}
        | #{f.radio_button :vc_possible_eq, false, id: "vc_possible_index_no"} #{t('game_rooms.index.sarch_vc_false')}


      .layout_none#layout_none
        .index_search_zone
          p = f.label t('game_rooms.index.sarch_skype')
          | #{f.radio_button :available_skype_eq, '', {:checked => true}}#{t('game_rooms.index.no_select')}
          | #{f.radio_button :available_skype_eq, true} #{t('game_rooms.index.sarch_skype_true')}
          | #{f.radio_button :available_skype_eq, false} #{t('game_rooms.index.sarch_skype_false')}

        .index_search_zone
          p = f.label t('game_rooms.index.sarch_discord')
          | #{f.radio_button :available_discord_eq, '', {:checked => true}}#{t('game_rooms.index.no_select')}
          | #{f.radio_button :available_discord_eq, true} #{t('game_rooms.index.sarch_discord_true')}
          | #{f.radio_button :available_discord_eq, false} #{t('game_rooms.index.sarch_discord_false')}

        .index_search_zone
          p = f.label t('game_rooms.index.sarch_ingame')
          | #{f.radio_button :available_ingame_vc_eq, '', {:checked => true}}#{t('game_rooms.index.no_select')}
          | #{f.radio_button :available_ingame_vc_eq, true} #{t('game_rooms.index.sarch_ingame_true')}
          | #{f.radio_button :available_ingame_vc_eq, false} #{t('game_rooms.index.sarch_ingame_false')}

      .index_search_zone
        p = f.label t('game_rooms.index.play_device')
        | #{f.radio_button :play_device_eq, '', {:checked => true}}#{t('game_rooms.index.no_select')}
        | #{f.radio_button :play_device_eq, 0} #{t('game_rooms.index.sarch_device_playstation')}
        | #{f.radio_button :play_device_eq, 1} #{t('game_rooms.index.sarch_device_nintendo')}
        | #{f.radio_button :play_device_eq, 2} #{t('game_rooms.index.sarch_device_steam')}

      .index_search_zone
        p.sarch_button = f.submit t('game_rooms.index.sarch')

  = sort_link(@q, :start_time, t('game_rooms.index.start_time_sort'))

hr.my-5/
section.text-center.layout-kaminari
  .row.mb-4.wow.fadeIn
    - @game_rooms.each do|gr|
      .col-lg-4.col-md-12.mb-4
        .card
          .card-body.testdiv.no_border
            h4.card-title.font-italic = gr.game_title
            - if user_signed_in?
              - if can_make_request(gr)
                - if condition_fullfill(current_user, gr)
                  p = link_to t('game_rooms.index.hope_to'), participants_path(user_id: gr.id), method: :post, class: "inlink btn btn-primary", notice: t('game_rooms.index.hope')
                - else
                  = render 'index_input_form', gameroom: gr
              - else
                p = link_to t('game_rooms.index.show'), game_room_path(gr.id), class: "index_show_button btn btn-primary"
            p.card-text
              .room_title.room_items
                p = gr.room_name
            p.card-text
              .room_device.room_items
                p.device_button = gr.play_device
            p.card-text
              - if gr.comment.present?
                .room_comment.room_items
                  p = t('game_rooms.index.comment')
                  p = gr.comment

            p.card-text
              - if gr.vc_possible == true
                .room_vc.room_items
                  p = t('game_rooms.index.available_vc')
            p.card-text
              - if gr.available_skype == true
                .room_skype.room_items
                  p = t('game_rooms.index.available_skype')
            p.card-text
              - if gr.available_discord == true
                .room_discord.room_items
                  p = t('game_rooms.index.available_discord')
            p.card-text
              - if gr.available_ingame_vc == true
                .room_ingame_vc.room_items
                  p = t('game_rooms.index.available_ingame')
            p.card-text
              .room_start_time.room_items.text-align-left
                p = t('game_rooms.index.start_time')
                p = gr.start_time.strftime("%y年%m月%d日 %H:%M:%S")
            p.card-text
              .room_play_time.room_items.text-align-left
                p = t('game_rooms.index.play_time')
                p = "#{gr.play_time} #{t('game_rooms.index.hour')}"
            p.card-text
              .room_owner_name.room_items.text-align-right
                p = t('game_rooms.index.owner_name')
                = find_owner_info(gr).name
            p.card-text
              - if gr.available_twitter == true
                .room_twitter.room_items.text-align-right
                  i.fab.fa-twitter-square.mr8.fa-lg
                  = find_owner_info(gr).twitter_address
              - else gr.open_twitter == true
                .room_twitter.room_items.text-align-right
                  i.fab.fa-twitter-square.mr8.fa-lg
                  = find_owner_info(gr).twitter_address
  = paginate @game_rooms, theme: 'twitter-bootstrap-4'

app/views/game_rooms/new.slim
h1 = t('game_rooms.new.title')
- if @game_room.errors.any?
  #error_explanatsion
    ul
      - @game_room.errors.full_messages.each do |message|
        li = message


.game_room_new
  = form_with(model: @game_room, local: true) do |f|
    .form-group
      = f.label t('game_rooms.new.room_name'), class: "control-label"
      = f.text_field :room_name, class: "form-control"

    .form-group
      = f.label t('game_rooms.new.game_title'), class: "control-label"
      = f.text_field :game_title, class: "form-control", id: "game_title"
      .game_tag.container
        - @game_titles.each_with_index do |title, x|
          button type="button" class="btn btn-primary mr6 mb6" id="tag_#{x + 1}"
            = title



    .form-group
      = f.label t('game_rooms.new.comment'), class: "control-label"
      = f.text_area :comment, class: "comment", placeholder: "募集の詳細。記入しておくことで他のユーザーが参加しやすくなるかもしれません。"

    .form-group
      = f.label t('game_rooms.new.vc'), class: "control-label", id: "test"
      .checkbox
        = f.check_box :vc_possible, id: "vc_possible"

    .layout_none#layout_none
      .form-group
        = f.label t('game_rooms.new.skype'), class: "control-label"
        .checkbox
          = f.check_box :available_skype

      .form-group
        = f.label t('game_rooms.new.discord'), class: "control-label"
        .checkbox
          = f.check_box :available_discord

      .form-group
        = f.label t('game_rooms.new.ingame'), class: "control-label"
        .checkbox
          = f.check_box :available_ingame_vc

    .form-group
      = f.label t('game_rooms.new.twitter'), class: "control-label"
      .checkbox
        = f.check_box :available_twitter

    .form-group
      = f.label t('game_rooms.new.start_time')
      = f.datetime_field :start_time, min: Date.today

    .form-group
      = f.label t('game_rooms.new.play_time'), class: "control-label"
      = f.select :play_time, [[t('game_rooms.new.1hour'), 1], [t('game_rooms.new.2hour'), 2], [t('game_rooms.new.3hour'), 3], [t('game_rooms.new.4hour'), 4], [t('game_rooms.new.5hour'), 5]], { selected: 1}, class: 'sample form-control'

    .form-group
      = f.label t('game_rooms.new.play_device'), class: "control-label"
      = f.select :play_device, GameRoom.play_devices.keys.to_a, {}, class: "form-control"

    .form-group
      = f.label t('game_rooms.new.open_twitter'), class: "control-label"
      .checkbox
        = f.check_box :open_twitter

    .form-group
      = f.label t('game_rooms.new.close_message'), class: "control-label"
      = f.text_area :close_message, placeholder: "参加が確定した人に対してしてほしいこと、ゲームを始めるまでの簡単な流れを書いておくとスムーズにマッチングできるかもしれません。例）予定時間の前までにゲーム内でフレンド申請を送ってください", class: "close_message"

    .form-group
      = f.submit t('game_rooms.new.submit'), class: "btn-lg btn-block  btn-primary"

app/views/game_rooms/show.slim
.game_room_show
  h1.mb60.text-align-center = t('game_rooms.show.title')

  .game_rooms_user_index
    h2
      i.fa.fa-user.mr10
      = t('game_rooms.show.user_index')

    - @participants.each do |user|
      .game_room_participants.mt20
        p = user.user.name
        - if current_user.id == @owner.user_id && user.id != current_user.id && user.state == "参加希望者"
          p.mt5 = user.state
          = link_to t('game_rooms.show.submit'), participant_path(user, room_id: @game_room.id), method: :patch
        - else
          p.mt5 = user.state
        - if current_user.id == @owner.user_id && @game_room.available_twitter == true
          p.mt5
            i.fab.fa-twitter-square.mr8.fa-lg
            = user.user.twitter_address
        - elsif @game_room.open_twitter
          p.mt5
            i.fab.fa-twitter-square.mr8.fa-lg
            = user.user.twitter_address

        - if @game_room.available_discord == true && (user.state == t('game_rooms.show.room_owner') || user.state == t('game_rooms.show.room_ok'))
          p.mt5
            i.fab.fa-discord.mr8.fa-lg
            = user.user.discord_id

        - if @game_room.available_skype == true && (user.state == t('game_rooms.show.room_owner') || user.state == t('game_rooms.show.room_ok'))
          p.mt5
            i.fab.fa-skype.mr8.fa-lg
            = user.user.skype_id

        - if @game_room.play_device == "PlayStation"
          p.mt5
            i.fab.fa-playstation.mr8.fa-lg
            = user.user.game_machines.find_by(game_device: "PlayStation").device_id

        - elsif @game_room.play_device == "Nintendo"
          p.mt5
            i.fas.fa-gamepad.mr8.fa-lg
            = user.user.game_machines.find_by(game_device: "Nintendo").device_id

        - else @game_room.play_device == "Steam"
          p.mt5
            i.fab.fa-steam-square
            = user.user.game_machines.find_by(game_device: "Steam").device_id

        - if current_user.id == @owner.user_id && user.state != t('game_rooms.show.room_owner')
          p = link_to t('game_rooms.show.kick'), participant_path(user_id: user.user_id, room_id: @game_room.id), method: :delete



  - if @participants.where("(user_id = ?) OR (state = ?) OR (state = ?)", current_user.id, 2, 0) && @game_room.close_message.present?
    h2.mt40
      i.fas.fa-sticky-note.mr8
      = t('game_rooms.show.close_message')
    p.pl20.pr20.mt20= @game_room.close_message

  / - if @participants.where("(user_id = ?) OR (state = ?) OR (state = ?)", current_user.id, 2, 0)
  - if @participants.find_by(user_id: current_user.id).present?
    - if @participants.find_by(user_id: current_user.id).state == "募集主" or @participants.find_by(user_id: current_user.id).state == "参加確定者"
      #message_box.mt40
        #comments_area
          = render 'game_room_messages/index'
          = render @messages
        = render 'game_room_messages/form', room_id: @game_room.id

  .show_game_room.mt40
    .room_game_title.room_items
      h2
        = @game_room.game_title
        - if current_user.id == @owner.user_id
          span.edit_link= link_to t('game_rooms.show.edit_link'), edit_game_room_path(@game_room)

    .room_title.room_items.mt30
      p = @game_room.room_name

    .room_comment.room_items.mt15
      p = t('game_rooms.show.comment')
      p = @game_room.comment

    .room_vc.room_items.mt15
      - if @game_room.vc_possible == true
        p = t('game_rooms.show.available_vc')
      - else
        p = t('game_rooms.show.no_vc')

    .room_skype.room_items.mt15
      - if @game_room.available_skype == true
        p = t('game_rooms.show.available_skype')

    .room_discord.room_items.mt15
      - if @game_room.available_discord
        p = t('game_rooms.show.available_discord')

    .room_ingame_vc.room_items.mt15
      - if @game_room.available_ingame_vc
        p = t('game_rooms.show.available_ingame')

    .room_twitter.room_items.mt15
      - if @game_room.available_twitter
        p = t('game_rooms.show.open_twitter')

    .room_start_time.room_items.mt15
      p = t('game_rooms.show.start_time')
      p = @game_room.start_time.strftime("%m月%d日 %H:%M")

    .room_play_time.room_items.mt15
      p = t('game_rooms.show.play_time')
      p = "#{@game_room.play_time} #{t('game_rooms.show.hour')}"

    .room_device.room_items.mt15
      p = t('game_rooms.show.game_device')
      p = @game_room.play_device

    .room_twitter.room_items.mt15
      - if @game_room.open_twitter
        p = t('game_rooms.show.twitter_all')