config/routes.rb
Rails.application.routes.draw do
  root to: "game_rooms#index"
  # devise_scope :user do
  #   root "users/sessions#new"
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  resources :users, only: %i!show!
  resources :game_rooms, only: %i!index new create edit update show destroy!
  resources :participants, only: %i! create update destroy!
  resources :game_room_messages, only: %i! create destroy!

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord

  before_create :ensure_has_name
  before_update :ensure_has_name

  acts_as_paranoid

  # devise
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :omniauthable, :confirmable

  has_many :game_machines, dependent: :destroy
  has_many :participants, class_name: "Participant", foreign_key: "user_id", dependent: :destroy
  has_many :game_rooms, through: :participants
  has_many :game_room_messages, dependent: :destroy, class_name: 'GameRoomMessage', foreign_key: 'write_user_id'
  has_many :message, dependent: :destroy
  has_many :chat_groups, dependent: :destroy

  accepts_nested_attributes_for :game_machines

  # devise facebook認証 自動ログイン
  def self.find_for_oauth(auth)
    user = User.find_by(uid: auth.uid, provider: auth.provider)

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
      game_machine = user.game_machines.build(game_device: "Nintendo", device_id: "")
      game_machine.save
      game_machine = user.game_machines.build(game_device: "PlayStation", device_id: "")
      game_machine.save
      game_machine = user.game_machines.build(game_device: "Steam", device_id: "")
      game_machine.save
    end
    user.skip_confirmation!
    user.save
    user
  end

  private

  def ensure_has_name
    self.name = '名無しさん' if name.blank?
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    callback_from :facebook
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  private
  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super

  #    @game_devices =
  #      ["playstation", "nintendo", "steam"].reduce([]) do |a, b|
  #        a << @user.game_machines.build(game_device: b)
  #      end
  # end


  # def create
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end
  # PUT /resource
  def update
    if params[:room_info]
      self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
      prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
      resource_updated = update_resource(resource, account_update_params)
      yield resource if block_given?
      if resource_updated
        set_flash_message_for_update(resource, prev_unconfirmed_email)
        bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      ############################ my
        @participant = Participant.new(user_id: current_user.id, state: 1, game_room_id: params[:room_info])
        @current_user = current_user
        @owner_user = GameRoom.find(params[:room_info]).participants.find_by(state: 0)
        if @participant.save
          GameRoomMailer.request_mail(@current_user, @owner_user).deliver
          flash[:notice] = "ユーザー情報を更新して参加しました"
        end
        ###############################################
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    else
      super
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # def configure_sign_up_params
  #   device_parameter_sanitizer.permit(:sign_up) do |params|
  #     params.permit(:name, game_machines_attributes: [:game_device, :device_id])
  #   end
  # end
  #
  # def user_params
  #   device_parameter_sanitizer.permit(:user) do |params|
  #     params.permit(:name, game_machines_attributes: [:game_device, :device_id, :name])
  #   end
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])

    @owner_room = []
    @owner_room_id = []
    @user.participants.where(state: 0).each do |x|
      @owner_room_id.push(x.game_room_id)
    end
    @owner_room_id.each do |x|
      @owner_room.push GameRoom.find(x)
    end
    # day = Date.today - 1
    # @owner_room.where('start_time >= ?', day)

    @hope_room = []
    @hope_room_id = []
    @user.participants.where(state: 1).each do |x|
      @hope_room_id.push(x.game_room_id)
    end
    @hope_room_id.each do |x|
      @hope_room.push GameRoom.find(x)
    end

    @participants_room = []
    @participants_room_id = []
    @user.participants.where(state: 2).each do |x|
      @participants_room_id.push(x.game_room_id)
    end
    @participants_room_id.each do |x|
      @participants_room.push GameRoom.find(x)
    end

    @game_machine = @user.game_machines
  end
end

app/views/users/show.html.slim
.user_show.container
  .profile.text-align-center
    h1.mb30
      i.fas.fa-user
      = "#{@user.name}のマイページ"
    .user_item
      p.mb0 = t('users.show.email')
      p = @user.email
    .user_item
      p.mb0 = t('users.show.profile')
      p = @user.profile
    .user_item
      p.mb0 = t('users.show.twitter_address')
      p = @user.twitter_address
    .user_item
      p.mb0 = t('users.show.skype_address')
      p = @user.skype_id
    .user_item
      p.mb0 = t('users.show.discord_id')
      p = @user.discord_id
    - @game_machine.each do |gm|
      .user_item
        p.mb0 = gm.game_device
        p = gm.device_id
    = link_to t('layout.profile_change'), edit_user_registration_path, class: "btn btn-primary"
  .rooms.mt40
    - if @owner_room.count > 0
      section#sec.row.container-fluid
        h2.col-md-12 = t('users.show.game_owner_rooms')
        ul.container-fluid
          - @owner_room.each do |gm|
            li.mypage_game_rooms.col-md-4.col-sm-6.col-lg-4
              h3.game_room_title = gm.game_title
              p.pt30 = gm.room_name
              p = gm.game_title
              p = gm.close_message
              p = gm.start_time.strftime("%m月%d日 %H:%M")
              p = "#{gm.play_time} 時間"
              - if gm.participants.find_by(state: 0).user_id == current_user.id
                p 募集主です
              = link_to t('users.show.room_show'), game_room_path(gm.id), class: "btn btn-primary room_show"

    - if @participants_room.count > 0
      section#sec.row.container-fluid
        h2.col-md-12 = t('users.show.game_participants_rooms')
        ul.container-fluid
          - @participants_room.each do |gm|
            li.mypage_game_rooms.col-md-4.col-sm-6.col-lg-4
              h3.game_room_title = gm.game_title
              p.pt30 = gm.room_name
              p = gm.game_title
              p = gm.close_message
              p = gm.start_time.strftime("%m月%d日 %H:%M")
              p = "#{gm.play_time} 時間"
              - if gm.participants.find_by(state: 2).user.id == current_user.id
                p 参加中です
              = link_to t('users.show.room_show'), game_room_path(gm.id), class: "btn btn-primary room_show"

    - if @hope_room.count > 0
      section#sec.row.container-fluid
        h2.col-md-12 = t('users.show.game_participants_rooms')
        ul.container-fluid
          - @hope_room.each do |gm|
            li.mypage_game_rooms.col-md-4.col-sm-6.col-lg-4
              h3.game_room_title = gm.game_title
              p.pt30 = gm.room_name
              p = gm.game_title
              p = gm.close_message
              p = gm.start_time.strftime("%m月%d日 %H:%M")
              p = "#{gm.play_time} 時間"
              - if gm.participants.find_by(state: 1).user.id == current_user.id
                p 参加申請中です
              = link_to t('users.show.room_show'), game_room_path(gm.id), class: "btn btn-primary room_show"





/   - if @participants.find_by(participant_id: current_user.id)
/     p = @game_room.close_message
/     p "参加者限定のメッセージです"

/ - if @participants.find_by(participant_id: current_user.id)
/   #message_box
/     #comments_area
/       = render partial: 'game_room_messages/index'
/     = render partial: 'game_room_messages/form'

/ .show_game_room
/   .room_game_title.room_items
/     p = t('game_rooms.show.game_title')
/     p = @game_room.game_title

/   .room_title.room_items
/     p = t('game_rooms.show.room_title')
/     p = @game_room.room_name

/   .room_comment.room_items
/     p = t('game_rooms.show.comment')
/     p = @game_room.comment

/   .room_vc.room_items
/     p = t('game_rooms.show.available_vc')
/     p = @game_room.vc_possible

/   .room_skype.room_items
/     p = t('game_rooms.show.available_skype')
/     p = @game_room.available_skype

/   .room_discord.room_items
/     p = t('game_rooms.show.available_discord')
/     p = @game_room.available_discord

/   .room_ingame_vc.room_items
/     p = t('game_rooms.show.available_ingame')
/     p = @game_room.available_ingame_vc

/   .room_twitter.room_items
/     p = t('game_rooms.show.open_twitter')
/     p = @game_room.available_twitter

/   .room_start_time.room_items
/     p = t('game_rooms.show.start_time')
/     p = @game_room.start_time

/   .room_play_time.room_items
/     p = t('game_rooms.show.play_time')
/     p = "#{@game_room.play_time} #{t('game_rooms.show.hour')}"

/   .room_device.room_items
/     p = t('game_rooms.show.game_device')
/     p = @game_room.play_device

/   .room_twitter.room_items
/     p = t('game_rooms.show.twitter_all')
/     p = @game_room.open_twitter