config/routes.rb
Rails.application.routes.draw do
  root to: "game_rooms#index"
  # devise_scope :user do
  #   root "users/sessions#new"
  # end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  resources :users, only: %i!show!
  resources :game_rooms, only: %i!index new create edit update show destroy!
  resources :participants, only: %i! create update destroy!
  resources :game_room_messages, only: %i! create destroy!

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | BetterExperience
    link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
    link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.12.0/css/mdb.min.css" rel="stylesheet"
    link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet"
    link href="https://fonts.googleapis.com/css?family=Libre+Baskerville&display=swap" rel="stylesheet"



    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'


    link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet"

  body
    header.container-fluid
      nav.navbar.navbar-expand-lg.navbar-dark
        = link_to "BetterExperience", game_rooms_path, {class: "navbar-brand"}
        button.navbar-toggler aria-controls="basicExampleNav" aria-expanded="false" aria-label=("Toggle navigation") data-target="#basicExampleNav" data-toggle="collapse" type="button"
          span.navbar-toggler-icon
        #basicExampleNav.collapse.navbar-collapse
          ul.navbar-nav.mr-auto
            - if user_signed_in?
              li.nav-item.active
                = link_to t('layout.mypage'), user_path(current_user.id), {class: "nav-link"}
              li.nav-item.active
                = link_to t('layout.logout'), destroy_user_session_path, {class: "nav-link"}
              li.nav-item.active
                = link_to t('layout.play'), new_game_room_path, {class: "nav-link"}
            - else
              li.nav-item.active
                = link_to t('layout.sign_in'), new_user_registration_path, {class: "nav-link"}
                span.sr-only (current)
              li.nav-item.active
                = link_to t('layout.log_in'), new_user_session_path, {class: "nav-link"}
    .test

      .wrap.container
        .error
          p.notice.mt20 = notice
          p.alert = alert

        = yield

    footer.container-fluid
      .footer_content.container
        p = t('layout.footer_copylight')